---
version: 2
multicolumn: false
web-width: 500px
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/Screen Shot 2019-11-26 at 11-06-05 AM/Screen Shot 2019-11-26 at
      11-06-05 AM.png
    type: static
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    url: "/users/271872/articles/410154/master/file/figures/Screen%20Shot%202019-11-26%20at%2011-06-05%20AM/Screen%20Shot%202019-11-26%20at%2011-06-05%20AM.png"
    folder_url: "/users/271872/articles/410154/master/folder/figures/Screen Shot 2019-11-26
      at 11-06-05 AM"
